from typing import Tuple, List
from sre_constants import _NamedIntConstant as SreNamedIntConstant  # type: ignore

def parse(pattern: str) -> List[Tuple[SreNamedIntConstant, int]]: ...

class SubPattern:
    ...

    def __iter__(self) -> 'SubPattern': ...
    def __next__(self) -> Tuple[SreNamedIntConstant, int]: ...
    def __getitem__(self, index: int) -> Tuple[SreNamedIntConstant, int]: ...
